import type { Metadata } from 'next';

import './styles.css';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="bg-slate-100 text-slate-900 dark:bg-slate-900 dark:text-slate-100">{children}</body>
    </html>
  );
};

export default RootLayout;
