/* eslint-disable no-console -- this is a build/codegen script that reports progress to stdout */
/**
 * Extracts the `to` route union from apps/web's generated `route-tree.ts` and writes it as a
 * standalone, import-free declaration (`src/generated/route.d.ts`) that the test suite consumes
 * for type-safe navigation.
 *
 * Why not import the type directly? `route-tree.ts` has top-level runtime imports of every route
 * module, so referencing its types drags the entire `apps/web` source graph (and its `@/*` aliases
 * and Vite globals) into the `testing` type-check program. Materializing just the string-literal
 * union severs that dependency.
 *
 * The output is git-ignored and regenerated on `postinstall` (so fresh clones and the IDE see it)
 * and again before `lint`/`test` (so it stays current if the route tree changed).
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

import ts from 'typescript';

const ROUTE_TREE_PATH = path.resolve(import.meta.dirname, '../../apps/web/src/route-tree.ts');
const OUTPUT_PATH = path.resolve(import.meta.dirname, '../src/generated/route.d.ts');

function extractRouteToMembers(sourceText: string): string[] {
  const sourceFile = ts.createSourceFile('route-tree.ts', sourceText, ts.ScriptTarget.Latest, true);

  let members: null | string[] = null;
  const visit = (node: ts.Node): void => {
    if (ts.isInterfaceDeclaration(node) && node.name.text === 'FileRouteTypes') {
      const toProperty = node.members.find(
        (member): member is ts.PropertySignature =>
          ts.isPropertySignature(member) && member.name.getText(sourceFile) === 'to'
      );
      if (toProperty?.type && ts.isUnionTypeNode(toProperty.type)) {
        members = toProperty.type.types.flatMap((typeNode) => {
          if (ts.isLiteralTypeNode(typeNode) && ts.isStringLiteral(typeNode.literal)) {
            return [typeNode.literal.text];
          }
          return [];
        });
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(sourceFile);

  if (!members) {
    throw new Error("Could not find `FileRouteTypes['to']` string-literal union in route-tree.ts");
  }
  return members;
}

function render(members: string[]): string {
  const union = members.map((member) => `  | '${member}'`).join('\n');
  return (
    '/* eslint-disable */\n' +
    '// AUTO-GENERATED by scripts/gen-routes.ts — do not edit by hand.\n' +
    '// Regenerate with: pnpm --filter @opendatacapture/testing gen:routes\n' +
    '\n' +
    `export type RouteTo =\n${union};\n`
  );
}

const sourceText = fs.readFileSync(ROUTE_TREE_PATH, 'utf8');
const generated = render(extractRouteToMembers(sourceText));

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, generated, 'utf8');
console.log(`Wrote ${path.relative(process.cwd(), OUTPUT_PATH)}`);
