catalog:
  '@casl/ability': ^6.7.1
  '@casl/prisma': ^1.4.1
  '@douglasneuroinformatics/esbuild-plugin-prisma': latest
  '@douglasneuroinformatics/eslint-config': latest
  '@douglasneuroinformatics/libcrypto': latest
  '@douglasneuroinformatics/libjs': latest
  '@douglasneuroinformatics/libnest': ^0.5.1
  '@douglasneuroinformatics/libpasswd': latest
  '@douglasneuroinformatics/libstats': latest
  '@douglasneuroinformatics/libui': ^3.8.6
  '@douglasneuroinformatics/libui-form-types': latest
  '@douglasneuroinformatics/prettier-config': latest
  '@douglasneuroinformatics/tsconfig': latest
  '@microsoft/api-extractor': ^7.47.6
  '@prisma/client': ^5.18.0
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.5.0
  '@testing-library/react': ^16.0.1
  '@testing-library/user-event': ^14.5.2
  axios: '^1.7.7'
  esbuild: 0.23.x
  esbuild-wasm: 0.23.x
  happy-dom: ^15.7.4
  nodemon: ^3.1.4
  prisma: ^5.18.0
  tsx: 4.8.2
  vite: ^5.4.12
packages:
  - apps/*
  - packages/*
  - runtime/*
  - testing/*
  - vendor/**/*
