catalog:
  '@casl/ability': ^6.7.1
  '@casl/prisma': ^1.4.1
  '@douglasneuroinformatics/esbuild-plugin-prisma': latest
  '@douglasneuroinformatics/libcrypto': ^0.0.4
  '@douglasneuroinformatics/libjs': ^1.3.1
  '@douglasneuroinformatics/libnest': ^0.5.1
  '@douglasneuroinformatics/libpasswd': latest
  '@douglasneuroinformatics/libstats': latest
  '@douglasneuroinformatics/libui': ^3.8.7
  '@douglasneuroinformatics/libui-form-types': latest
  '@microsoft/api-extractor': ^7.47.6
  '@prisma/client': ^6.5.0
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.5.0
  '@testing-library/react': ^16.0.1
  '@testing-library/user-event': ^14.5.2
  axios: '^1.8.2'
  esbuild: 0.23.x
  esbuild-wasm: 0.23.x
  happy-dom: ^15.7.4
  motion: 11.15.0
  nodemon: ^3.1.9
  prisma: ^6.5.0
  tsx: 4.8.2
  vite: ^5.4.12
packages:
  - apps/*
  - packages/*
  - runtime/*
  - testing/*
  - vendor/**/*
