---
catalog:
  '@casl/ability': '^6.7.1'
  '@casl/prisma': '^1.4.1'
  '@douglasneuroinformatics/esbuild-plugin-prisma': 'latest'
  '@douglasneuroinformatics/libcrypto': '^0.0.4'
  '@douglasneuroinformatics/libjs': ^3.1.0
  '@douglasneuroinformatics/libpasswd': 'latest'
  '@douglasneuroinformatics/libstats': 'latest'
  '@douglasneuroinformatics/libui': ^4.8.1
  '@douglasneuroinformatics/libui-form-types': 'latest'
  '@microsoft/api-extractor': '^7.47.6'
  '@prisma/client': '^6.9.0'
  '@tailwindcss/vite': '^4.1.4'
  '@testing-library/dom': '^10.4.0'
  '@testing-library/jest-dom': '^6.5.0'
  '@testing-library/react': '^16.0.1'
  '@testing-library/user-event': '^14.5.2'
  axios: '^1.12.0'
  esbuild: '0.23.x'
  esbuild-wasm: '0.23.x'
  happy-dom: '^20.0.2'
  motion: '11.15.0'
  neverthrow: ^8.2.0
  nodemon: '^3.1.9'
  prisma: '^6.9.0'
  tailwindcss: '^4.1.4'
  tsx: '4.8.2'
  serialize-error: '^11.0.3'
  vite: '^6.3.3'
  '@storybook/addon-docs': '9.0.0-beta.3'
  '@storybook/addon-themes': '9.0.0-beta.3'
  '@storybook/react-vite': '9.0.0-beta.3'
  'storybook': '9.0.0-beta.3'
catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
packages:
  - 'apps/*'
  - 'packages/*'
  - 'runtime/*'
  - 'storybook'
  - 'testing/*'
  - 'vendor/**/*'
