/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppUserRouteImport } from './routes/_app/user'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AppAdminInstrumentsRouteImport } from './routes/_app/admin/instruments'
import { Route as AppAdminMailRouteImport } from './routes/_app/admin/mail'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppDatahubIndexRouteImport } from './routes/_app/datahub/index'
import { Route as AppGroupEmailTemplatesRouteImport } from './routes/_app/group/email-templates'
import { Route as AppGroupManageRouteImport } from './routes/_app/group/manage'
import { Route as AppGroupRemoteAssignmentsRouteImport } from './routes/_app/group/remote-assignments'
import { Route as AppInstrumentsAccessibleInstrumentsRouteImport } from './routes/_app/instruments/accessible-instruments'
import { Route as AppSessionRemoteAssignmentRouteImport } from './routes/_app/session/remote-assignment'
import { Route as AppSessionStartSessionRouteImport } from './routes/_app/session/start-session'
import { Route as AppUploadIndexRouteImport } from './routes/_app/upload/index'
import { Route as AppUploadInstrumentIdRouteImport } from './routes/_app/upload/$instrumentId'
import { Route as AppAdminAuditLogsRouteImport } from './routes/_app/admin/audit/logs'
import { Route as AppAdminBrandingIndexRouteImport } from './routes/_app/admin/branding/index'
import { Route as AppAdminBrandingLoginPageRouteImport } from './routes/_app/admin/branding/login-page'
import { Route as AppAdminGroupsIndexRouteImport } from './routes/_app/admin/groups/index'
import { Route as AppAdminGroupsCreateRouteImport } from './routes/_app/admin/groups/create'
import { Route as AppAdminInstrumentReposIndexRouteImport } from './routes/_app/admin/instrument-repos/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/_app/admin/users/$userId'
import { Route as AppAdminUsersCreateRouteImport } from './routes/_app/admin/users/create'
import { Route as AppDatahubSubjectsIndexRouteImport } from './routes/_app/datahub/subjects/index'
import { Route as AppDatahubSubjectsSubjectIdRouteRouteImport } from './routes/_app/datahub/subjects/$subjectId/route'
import { Route as AppInstrumentsRenderIdRouteImport } from './routes/_app/instruments/render/$id'
import { Route as AppDatahubSubjectsSubjectIdAssignmentsRouteImport } from './routes/_app/datahub/subjects/$subjectId/assignments'
import { Route as AppDatahubSubjectsSubjectIdGraphRouteImport } from './routes/_app/datahub/subjects/$subjectId/graph'
import { Route as AppDatahubSubjectsSubjectIdTableIndexRouteImport } from './routes/_app/datahub/subjects/$subjectId/table/index'
import { Route as AppDatahubSubjectsSubjectIdTableRecordIdRouteImport } from './routes/_app/datahub/subjects/$subjectId/table/$recordId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUserRoute = AppUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminInstrumentsRoute = AppAdminInstrumentsRouteImport.update({
  id: '/admin/instruments',
  path: '/admin/instruments',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminMailRoute = AppAdminMailRouteImport.update({
  id: '/admin/mail',
  path: '/admin/mail',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDatahubIndexRoute = AppDatahubIndexRouteImport.update({
  id: '/datahub/',
  path: '/datahub/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupEmailTemplatesRoute = AppGroupEmailTemplatesRouteImport.update({
  id: '/group/email-templates',
  path: '/group/email-templates',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupManageRoute = AppGroupManageRouteImport.update({
  id: '/group/manage',
  path: '/group/manage',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupRemoteAssignmentsRoute =
  AppGroupRemoteAssignmentsRouteImport.update({
    id: '/group/remote-assignments',
    path: '/group/remote-assignments',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppInstrumentsAccessibleInstrumentsRoute =
  AppInstrumentsAccessibleInstrumentsRouteImport.update({
    id: '/instruments/accessible-instruments',
    path: '/instruments/accessible-instruments',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSessionRemoteAssignmentRoute =
  AppSessionRemoteAssignmentRouteImport.update({
    id: '/session/remote-assignment',
    path: '/session/remote-assignment',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSessionStartSessionRoute = AppSessionStartSessionRouteImport.update({
  id: '/session/start-session',
  path: '/session/start-session',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUploadIndexRoute = AppUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUploadInstrumentIdRoute = AppUploadInstrumentIdRouteImport.update({
  id: '/upload/$instrumentId',
  path: '/upload/$instrumentId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminAuditLogsRoute = AppAdminAuditLogsRouteImport.update({
  id: '/admin/audit/logs',
  path: '/admin/audit/logs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminBrandingIndexRoute = AppAdminBrandingIndexRouteImport.update({
  id: '/admin/branding/',
  path: '/admin/branding/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminBrandingLoginPageRoute =
  AppAdminBrandingLoginPageRouteImport.update({
    id: '/admin/branding/login-page',
    path: '/admin/branding/login-page',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAdminGroupsIndexRoute = AppAdminGroupsIndexRouteImport.update({
  id: '/admin/groups/',
  path: '/admin/groups/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminGroupsCreateRoute = AppAdminGroupsCreateRouteImport.update({
  id: '/admin/groups/create',
  path: '/admin/groups/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminInstrumentReposIndexRoute =
  AppAdminInstrumentReposIndexRouteImport.update({
    id: '/admin/instrument-repos/',
    path: '/admin/instrument-repos/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUsersCreateRoute = AppAdminUsersCreateRouteImport.update({
  id: '/admin/users/create',
  path: '/admin/users/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDatahubSubjectsIndexRoute = AppDatahubSubjectsIndexRouteImport.update({
  id: '/datahub/subjects/',
  path: '/datahub/subjects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDatahubSubjectsSubjectIdRouteRoute =
  AppDatahubSubjectsSubjectIdRouteRouteImport.update({
    id: '/datahub/subjects/$subjectId',
    path: '/datahub/subjects/$subjectId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppInstrumentsRenderIdRoute = AppInstrumentsRenderIdRouteImport.update({
  id: '/instruments/render/$id',
  path: '/instruments/render/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDatahubSubjectsSubjectIdAssignmentsRoute =
  AppDatahubSubjectsSubjectIdAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AppDatahubSubjectsSubjectIdRouteRoute,
  } as any)
const AppDatahubSubjectsSubjectIdGraphRoute =
  AppDatahubSubjectsSubjectIdGraphRouteImport.update({
    id: '/graph',
    path: '/graph',
    getParentRoute: () => AppDatahubSubjectsSubjectIdRouteRoute,
  } as any)
const AppDatahubSubjectsSubjectIdTableIndexRoute =
  AppDatahubSubjectsSubjectIdTableIndexRouteImport.update({
    id: '/table/',
    path: '/table/',
    getParentRoute: () => AppDatahubSubjectsSubjectIdRouteRoute,
  } as any)
const AppDatahubSubjectsSubjectIdTableRecordIdRoute =
  AppDatahubSubjectsSubjectIdTableRecordIdRouteImport.update({
    id: '/table/$recordId',
    path: '/table/$recordId',
    getParentRoute: () => AppDatahubSubjectsSubjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/setup': typeof SetupRoute
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/user': typeof AppUserRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/instruments': typeof AppAdminInstrumentsRoute
  '/admin/mail': typeof AppAdminMailRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/group/email-templates': typeof AppGroupEmailTemplatesRoute
  '/group/manage': typeof AppGroupManageRoute
  '/group/remote-assignments': typeof AppGroupRemoteAssignmentsRoute
  '/instruments/accessible-instruments': typeof AppInstrumentsAccessibleInstrumentsRoute
  '/session/remote-assignment': typeof AppSessionRemoteAssignmentRoute
  '/session/start-session': typeof AppSessionStartSessionRoute
  '/upload/$instrumentId': typeof AppUploadInstrumentIdRoute
  '/datahub/': typeof AppDatahubIndexRoute
  '/upload/': typeof AppUploadIndexRoute
  '/datahub/subjects/$subjectId': typeof AppDatahubSubjectsSubjectIdRouteRouteWithChildren
  '/admin/audit/logs': typeof AppAdminAuditLogsRoute
  '/admin/branding/login-page': typeof AppAdminBrandingLoginPageRoute
  '/admin/groups/create': typeof AppAdminGroupsCreateRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/admin/users/create': typeof AppAdminUsersCreateRoute
  '/instruments/render/$id': typeof AppInstrumentsRenderIdRoute
  '/admin/branding/': typeof AppAdminBrandingIndexRoute
  '/admin/groups/': typeof AppAdminGroupsIndexRoute
  '/admin/instrument-repos/': typeof AppAdminInstrumentReposIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/datahub/subjects/': typeof AppDatahubSubjectsIndexRoute
  '/datahub/subjects/$subjectId/assignments': typeof AppDatahubSubjectsSubjectIdAssignmentsRoute
  '/datahub/subjects/$subjectId/graph': typeof AppDatahubSubjectsSubjectIdGraphRoute
  '/datahub/subjects/$subjectId/table/$recordId': typeof AppDatahubSubjectsSubjectIdTableRecordIdRoute
  '/datahub/subjects/$subjectId/table/': typeof AppDatahubSubjectsSubjectIdTableIndexRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/user': typeof AppUserRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AppIndexRoute
  '/admin/instruments': typeof AppAdminInstrumentsRoute
  '/admin/mail': typeof AppAdminMailRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/group/email-templates': typeof AppGroupEmailTemplatesRoute
  '/group/manage': typeof AppGroupManageRoute
  '/group/remote-assignments': typeof AppGroupRemoteAssignmentsRoute
  '/instruments/accessible-instruments': typeof AppInstrumentsAccessibleInstrumentsRoute
  '/session/remote-assignment': typeof AppSessionRemoteAssignmentRoute
  '/session/start-session': typeof AppSessionStartSessionRoute
  '/upload/$instrumentId': typeof AppUploadInstrumentIdRoute
  '/datahub': typeof AppDatahubIndexRoute
  '/upload': typeof AppUploadIndexRoute
  '/datahub/subjects/$subjectId': typeof AppDatahubSubjectsSubjectIdRouteRouteWithChildren
  '/admin/audit/logs': typeof AppAdminAuditLogsRoute
  '/admin/branding/login-page': typeof AppAdminBrandingLoginPageRoute
  '/admin/groups/create': typeof AppAdminGroupsCreateRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/admin/users/create': typeof AppAdminUsersCreateRoute
  '/instruments/render/$id': typeof AppInstrumentsRenderIdRoute
  '/admin/branding': typeof AppAdminBrandingIndexRoute
  '/admin/groups': typeof AppAdminGroupsIndexRoute
  '/admin/instrument-repos': typeof AppAdminInstrumentReposIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/datahub/subjects': typeof AppDatahubSubjectsIndexRoute
  '/datahub/subjects/$subjectId/assignments': typeof AppDatahubSubjectsSubjectIdAssignmentsRoute
  '/datahub/subjects/$subjectId/graph': typeof AppDatahubSubjectsSubjectIdGraphRoute
  '/datahub/subjects/$subjectId/table/$recordId': typeof AppDatahubSubjectsSubjectIdTableRecordIdRoute
  '/datahub/subjects/$subjectId/table': typeof AppDatahubSubjectsSubjectIdTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/user': typeof AppUserRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/instruments': typeof AppAdminInstrumentsRoute
  '/_app/admin/mail': typeof AppAdminMailRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/group/email-templates': typeof AppGroupEmailTemplatesRoute
  '/_app/group/manage': typeof AppGroupManageRoute
  '/_app/group/remote-assignments': typeof AppGroupRemoteAssignmentsRoute
  '/_app/instruments/accessible-instruments': typeof AppInstrumentsAccessibleInstrumentsRoute
  '/_app/session/remote-assignment': typeof AppSessionRemoteAssignmentRoute
  '/_app/session/start-session': typeof AppSessionStartSessionRoute
  '/_app/upload/$instrumentId': typeof AppUploadInstrumentIdRoute
  '/_app/datahub/': typeof AppDatahubIndexRoute
  '/_app/upload/': typeof AppUploadIndexRoute
  '/_app/datahub/subjects/$subjectId': typeof AppDatahubSubjectsSubjectIdRouteRouteWithChildren
  '/_app/admin/audit/logs': typeof AppAdminAuditLogsRoute
  '/_app/admin/branding/login-page': typeof AppAdminBrandingLoginPageRoute
  '/_app/admin/groups/create': typeof AppAdminGroupsCreateRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/_app/admin/users/create': typeof AppAdminUsersCreateRoute
  '/_app/instruments/render/$id': typeof AppInstrumentsRenderIdRoute
  '/_app/admin/branding/': typeof AppAdminBrandingIndexRoute
  '/_app/admin/groups/': typeof AppAdminGroupsIndexRoute
  '/_app/admin/instrument-repos/': typeof AppAdminInstrumentReposIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/datahub/subjects/': typeof AppDatahubSubjectsIndexRoute
  '/_app/datahub/subjects/$subjectId/assignments': typeof AppDatahubSubjectsSubjectIdAssignmentsRoute
  '/_app/datahub/subjects/$subjectId/graph': typeof AppDatahubSubjectsSubjectIdGraphRoute
  '/_app/datahub/subjects/$subjectId/table/$recordId': typeof AppDatahubSubjectsSubjectIdTableRecordIdRoute
  '/_app/datahub/subjects/$subjectId/table/': typeof AppDatahubSubjectsSubjectIdTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/user'
    | '/auth/login'
    | '/auth/reset-password'
    | '/admin/instruments'
    | '/admin/mail'
    | '/admin/settings'
    | '/group/email-templates'
    | '/group/manage'
    | '/group/remote-assignments'
    | '/instruments/accessible-instruments'
    | '/session/remote-assignment'
    | '/session/start-session'
    | '/upload/$instrumentId'
    | '/datahub/'
    | '/upload/'
    | '/datahub/subjects/$subjectId'
    | '/admin/audit/logs'
    | '/admin/branding/login-page'
    | '/admin/groups/create'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/instruments/render/$id'
    | '/admin/branding/'
    | '/admin/groups/'
    | '/admin/instrument-repos/'
    | '/admin/users/'
    | '/datahub/subjects/'
    | '/datahub/subjects/$subjectId/assignments'
    | '/datahub/subjects/$subjectId/graph'
    | '/datahub/subjects/$subjectId/table/$recordId'
    | '/datahub/subjects/$subjectId/table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/user'
    | '/auth/login'
    | '/auth/reset-password'
    | '/'
    | '/admin/instruments'
    | '/admin/mail'
    | '/admin/settings'
    | '/group/email-templates'
    | '/group/manage'
    | '/group/remote-assignments'
    | '/instruments/accessible-instruments'
    | '/session/remote-assignment'
    | '/session/start-session'
    | '/upload/$instrumentId'
    | '/datahub'
    | '/upload'
    | '/datahub/subjects/$subjectId'
    | '/admin/audit/logs'
    | '/admin/branding/login-page'
    | '/admin/groups/create'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/instruments/render/$id'
    | '/admin/branding'
    | '/admin/groups'
    | '/admin/instrument-repos'
    | '/admin/users'
    | '/datahub/subjects'
    | '/datahub/subjects/$subjectId/assignments'
    | '/datahub/subjects/$subjectId/graph'
    | '/datahub/subjects/$subjectId/table/$recordId'
    | '/datahub/subjects/$subjectId/table'
  id:
    | '__root__'
    | '/_app'
    | '/setup'
    | '/_app/about'
    | '/_app/contact'
    | '/_app/dashboard'
    | '/_app/user'
    | '/auth/login'
    | '/auth/reset-password'
    | '/_app/'
    | '/_app/admin/instruments'
    | '/_app/admin/mail'
    | '/_app/admin/settings'
    | '/_app/group/email-templates'
    | '/_app/group/manage'
    | '/_app/group/remote-assignments'
    | '/_app/instruments/accessible-instruments'
    | '/_app/session/remote-assignment'
    | '/_app/session/start-session'
    | '/_app/upload/$instrumentId'
    | '/_app/datahub/'
    | '/_app/upload/'
    | '/_app/datahub/subjects/$subjectId'
    | '/_app/admin/audit/logs'
    | '/_app/admin/branding/login-page'
    | '/_app/admin/groups/create'
    | '/_app/admin/users/$userId'
    | '/_app/admin/users/create'
    | '/_app/instruments/render/$id'
    | '/_app/admin/branding/'
    | '/_app/admin/groups/'
    | '/_app/admin/instrument-repos/'
    | '/_app/admin/users/'
    | '/_app/datahub/subjects/'
    | '/_app/datahub/subjects/$subjectId/assignments'
    | '/_app/datahub/subjects/$subjectId/graph'
    | '/_app/datahub/subjects/$subjectId/table/$recordId'
    | '/_app/datahub/subjects/$subjectId/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SetupRoute: typeof SetupRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/user': {
      id: '/_app/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppUserRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/instruments': {
      id: '/_app/admin/instruments'
      path: '/admin/instruments'
      fullPath: '/admin/instruments'
      preLoaderRoute: typeof AppAdminInstrumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/mail': {
      id: '/_app/admin/mail'
      path: '/admin/mail'
      fullPath: '/admin/mail'
      preLoaderRoute: typeof AppAdminMailRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/datahub/': {
      id: '/_app/datahub/'
      path: '/datahub'
      fullPath: '/datahub/'
      preLoaderRoute: typeof AppDatahubIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/group/email-templates': {
      id: '/_app/group/email-templates'
      path: '/group/email-templates'
      fullPath: '/group/email-templates'
      preLoaderRoute: typeof AppGroupEmailTemplatesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/group/manage': {
      id: '/_app/group/manage'
      path: '/group/manage'
      fullPath: '/group/manage'
      preLoaderRoute: typeof AppGroupManageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/group/remote-assignments': {
      id: '/_app/group/remote-assignments'
      path: '/group/remote-assignments'
      fullPath: '/group/remote-assignments'
      preLoaderRoute: typeof AppGroupRemoteAssignmentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/instruments/accessible-instruments': {
      id: '/_app/instruments/accessible-instruments'
      path: '/instruments/accessible-instruments'
      fullPath: '/instruments/accessible-instruments'
      preLoaderRoute: typeof AppInstrumentsAccessibleInstrumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/session/remote-assignment': {
      id: '/_app/session/remote-assignment'
      path: '/session/remote-assignment'
      fullPath: '/session/remote-assignment'
      preLoaderRoute: typeof AppSessionRemoteAssignmentRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/session/start-session': {
      id: '/_app/session/start-session'
      path: '/session/start-session'
      fullPath: '/session/start-session'
      preLoaderRoute: typeof AppSessionStartSessionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/upload/': {
      id: '/_app/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof AppUploadIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/upload/$instrumentId': {
      id: '/_app/upload/$instrumentId'
      path: '/upload/$instrumentId'
      fullPath: '/upload/$instrumentId'
      preLoaderRoute: typeof AppUploadInstrumentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/audit/logs': {
      id: '/_app/admin/audit/logs'
      path: '/admin/audit/logs'
      fullPath: '/admin/audit/logs'
      preLoaderRoute: typeof AppAdminAuditLogsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/branding/': {
      id: '/_app/admin/branding/'
      path: '/admin/branding'
      fullPath: '/admin/branding/'
      preLoaderRoute: typeof AppAdminBrandingIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/branding/login-page': {
      id: '/_app/admin/branding/login-page'
      path: '/admin/branding/login-page'
      fullPath: '/admin/branding/login-page'
      preLoaderRoute: typeof AppAdminBrandingLoginPageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/groups/': {
      id: '/_app/admin/groups/'
      path: '/admin/groups'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AppAdminGroupsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/groups/create': {
      id: '/_app/admin/groups/create'
      path: '/admin/groups/create'
      fullPath: '/admin/groups/create'
      preLoaderRoute: typeof AppAdminGroupsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/instrument-repos/': {
      id: '/_app/admin/instrument-repos/'
      path: '/admin/instrument-repos'
      fullPath: '/admin/instrument-repos/'
      preLoaderRoute: typeof AppAdminInstrumentReposIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/users/create': {
      id: '/_app/admin/users/create'
      path: '/admin/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AppAdminUsersCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/datahub/subjects/': {
      id: '/_app/datahub/subjects/'
      path: '/datahub/subjects'
      fullPath: '/datahub/subjects/'
      preLoaderRoute: typeof AppDatahubSubjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/datahub/subjects/$subjectId': {
      id: '/_app/datahub/subjects/$subjectId'
      path: '/datahub/subjects/$subjectId'
      fullPath: '/datahub/subjects/$subjectId'
      preLoaderRoute: typeof AppDatahubSubjectsSubjectIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/instruments/render/$id': {
      id: '/_app/instruments/render/$id'
      path: '/instruments/render/$id'
      fullPath: '/instruments/render/$id'
      preLoaderRoute: typeof AppInstrumentsRenderIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/datahub/subjects/$subjectId/assignments': {
      id: '/_app/datahub/subjects/$subjectId/assignments'
      path: '/assignments'
      fullPath: '/datahub/subjects/$subjectId/assignments'
      preLoaderRoute: typeof AppDatahubSubjectsSubjectIdAssignmentsRouteImport
      parentRoute: typeof AppDatahubSubjectsSubjectIdRouteRoute
    }
    '/_app/datahub/subjects/$subjectId/graph': {
      id: '/_app/datahub/subjects/$subjectId/graph'
      path: '/graph'
      fullPath: '/datahub/subjects/$subjectId/graph'
      preLoaderRoute: typeof AppDatahubSubjectsSubjectIdGraphRouteImport
      parentRoute: typeof AppDatahubSubjectsSubjectIdRouteRoute
    }
    '/_app/datahub/subjects/$subjectId/table/': {
      id: '/_app/datahub/subjects/$subjectId/table/'
      path: '/table'
      fullPath: '/datahub/subjects/$subjectId/table/'
      preLoaderRoute: typeof AppDatahubSubjectsSubjectIdTableIndexRouteImport
      parentRoute: typeof AppDatahubSubjectsSubjectIdRouteRoute
    }
    '/_app/datahub/subjects/$subjectId/table/$recordId': {
      id: '/_app/datahub/subjects/$subjectId/table/$recordId'
      path: '/table/$recordId'
      fullPath: '/datahub/subjects/$subjectId/table/$recordId'
      preLoaderRoute: typeof AppDatahubSubjectsSubjectIdTableRecordIdRouteImport
      parentRoute: typeof AppDatahubSubjectsSubjectIdRouteRoute
    }
  }
}

interface AppDatahubSubjectsSubjectIdRouteRouteChildren {
  AppDatahubSubjectsSubjectIdAssignmentsRoute: typeof AppDatahubSubjectsSubjectIdAssignmentsRoute
  AppDatahubSubjectsSubjectIdGraphRoute: typeof AppDatahubSubjectsSubjectIdGraphRoute
  AppDatahubSubjectsSubjectIdTableRecordIdRoute: typeof AppDatahubSubjectsSubjectIdTableRecordIdRoute
  AppDatahubSubjectsSubjectIdTableIndexRoute: typeof AppDatahubSubjectsSubjectIdTableIndexRoute
}

const AppDatahubSubjectsSubjectIdRouteRouteChildren: AppDatahubSubjectsSubjectIdRouteRouteChildren =
  {
    AppDatahubSubjectsSubjectIdAssignmentsRoute:
      AppDatahubSubjectsSubjectIdAssignmentsRoute,
    AppDatahubSubjectsSubjectIdGraphRoute:
      AppDatahubSubjectsSubjectIdGraphRoute,
    AppDatahubSubjectsSubjectIdTableRecordIdRoute:
      AppDatahubSubjectsSubjectIdTableRecordIdRoute,
    AppDatahubSubjectsSubjectIdTableIndexRoute:
      AppDatahubSubjectsSubjectIdTableIndexRoute,
  }

const AppDatahubSubjectsSubjectIdRouteRouteWithChildren =
  AppDatahubSubjectsSubjectIdRouteRoute._addFileChildren(
    AppDatahubSubjectsSubjectIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppContactRoute: typeof AppContactRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppUserRoute: typeof AppUserRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminInstrumentsRoute: typeof AppAdminInstrumentsRoute
  AppAdminMailRoute: typeof AppAdminMailRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppGroupEmailTemplatesRoute: typeof AppGroupEmailTemplatesRoute
  AppGroupManageRoute: typeof AppGroupManageRoute
  AppGroupRemoteAssignmentsRoute: typeof AppGroupRemoteAssignmentsRoute
  AppInstrumentsAccessibleInstrumentsRoute: typeof AppInstrumentsAccessibleInstrumentsRoute
  AppSessionRemoteAssignmentRoute: typeof AppSessionRemoteAssignmentRoute
  AppSessionStartSessionRoute: typeof AppSessionStartSessionRoute
  AppUploadInstrumentIdRoute: typeof AppUploadInstrumentIdRoute
  AppDatahubIndexRoute: typeof AppDatahubIndexRoute
  AppUploadIndexRoute: typeof AppUploadIndexRoute
  AppDatahubSubjectsSubjectIdRouteRoute: typeof AppDatahubSubjectsSubjectIdRouteRouteWithChildren
  AppAdminAuditLogsRoute: typeof AppAdminAuditLogsRoute
  AppAdminBrandingLoginPageRoute: typeof AppAdminBrandingLoginPageRoute
  AppAdminGroupsCreateRoute: typeof AppAdminGroupsCreateRoute
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
  AppAdminUsersCreateRoute: typeof AppAdminUsersCreateRoute
  AppInstrumentsRenderIdRoute: typeof AppInstrumentsRenderIdRoute
  AppAdminBrandingIndexRoute: typeof AppAdminBrandingIndexRoute
  AppAdminGroupsIndexRoute: typeof AppAdminGroupsIndexRoute
  AppAdminInstrumentReposIndexRoute: typeof AppAdminInstrumentReposIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppDatahubSubjectsIndexRoute: typeof AppDatahubSubjectsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppContactRoute: AppContactRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppUserRoute: AppUserRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminInstrumentsRoute: AppAdminInstrumentsRoute,
  AppAdminMailRoute: AppAdminMailRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppGroupEmailTemplatesRoute: AppGroupEmailTemplatesRoute,
  AppGroupManageRoute: AppGroupManageRoute,
  AppGroupRemoteAssignmentsRoute: AppGroupRemoteAssignmentsRoute,
  AppInstrumentsAccessibleInstrumentsRoute:
    AppInstrumentsAccessibleInstrumentsRoute,
  AppSessionRemoteAssignmentRoute: AppSessionRemoteAssignmentRoute,
  AppSessionStartSessionRoute: AppSessionStartSessionRoute,
  AppUploadInstrumentIdRoute: AppUploadInstrumentIdRoute,
  AppDatahubIndexRoute: AppDatahubIndexRoute,
  AppUploadIndexRoute: AppUploadIndexRoute,
  AppDatahubSubjectsSubjectIdRouteRoute:
    AppDatahubSubjectsSubjectIdRouteRouteWithChildren,
  AppAdminAuditLogsRoute: AppAdminAuditLogsRoute,
  AppAdminBrandingLoginPageRoute: AppAdminBrandingLoginPageRoute,
  AppAdminGroupsCreateRoute: AppAdminGroupsCreateRoute,
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
  AppAdminUsersCreateRoute: AppAdminUsersCreateRoute,
  AppInstrumentsRenderIdRoute: AppInstrumentsRenderIdRoute,
  AppAdminBrandingIndexRoute: AppAdminBrandingIndexRoute,
  AppAdminGroupsIndexRoute: AppAdminGroupsIndexRoute,
  AppAdminInstrumentReposIndexRoute: AppAdminInstrumentReposIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppDatahubSubjectsIndexRoute: AppDatahubSubjectsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  SetupRoute: SetupRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
