import type { Metadata } from 'next';

import './styles.css';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html className="h-full" lang="en">
      <body className="h-full">{children}</body>
    </html>
  );
};

export default RootLayout;
