export default {
  include: [
    '@opendatacapture/evaluate-instrument',
    '@opendatacapture/runtime-core',
    '@opendatacapture/licenses',
    '@jspsych/plugin-html-button-response__1.x',
    '@jspsych/plugin-html-button-response__1.x',
    '@jspsych/plugin-html-keyboard-response__1.x',
    '@jspsych/plugin-html-keyboard-response__2.x',
    '@jspsych/plugin-image-button-response__1.x',
    '@jspsych/plugin-image-button-response__2.x',
    '@jspsych/plugin-image-keyboard-response__1.x',
    '@jspsych/plugin-image-keyboard-response__2.x',
    '@jspsych/plugin-preload__1.x',
    '@jspsych/plugin-preload__2.x',
    '@jspsych/plugin-survey-html-form__1.x',
    '@jspsych/plugin-survey-html-form__2.x',
    '@jspsych/plugin-survey-text__1.x',
    '@jspsych/plugin-survey-text__2.x',
    'csstype__3.x',
    'dompurify__3.x',
    'jquery__1.12.4',
    'jspsych__7.x',
    'jspsych__8.x',
    'lodash-es__4.x',
    'normalize.css__8.x',
    'papaparse__5.x',
    'prop-types__15.x',
    'pure-rand__6.x',
    'react-dom__18.x',
    'react__18.x',
    'simple-statistics__7.x',
    'ts-pattern__5.x',
    'type-fest__4.x',
    'zod__3.23.x'
  ],
  mode: 'production',
  outdir: 'dist'
};
