export default {
  include: [
    '@opendatacapture/evaluate-instrument',
    '@opendatacapture/runtime-core',
    '@opendatacapture/licenses',
    '@jspsych/plugin-html-button-response__1.2.0',
    '@jspsych/plugin-html-button-response__1.2.0',
    '@jspsych/plugin-html-keyboard-response__1.1.3',
    '@jspsych/plugin-html-keyboard-response__2.0.0',
    '@jspsych/plugin-image-button-response__1.2.0',
    '@jspsych/plugin-image-button-response__2.0.0',
    '@jspsych/plugin-image-keyboard-response__1.1.3',
    '@jspsych/plugin-image-keyboard-response__2.0.0',
    '@jspsych/plugin-preload__1.1.3',
    '@jspsych/plugin-preload__2.0.0',
    '@jspsych/plugin-survey-html-form__1.0.3',
    '@jspsych/plugin-survey-html-form__2.0.0',
    '@jspsych/plugin-survey-text__1.1.3',
    '@jspsych/plugin-survey-text__2.0.0',
    'dompurify__3.1.6',
    'jquery__1.12.4',
    'jspsych__7.3.4',
    'jspsych__8.0.1',
    'lodash-es__4.17.21',
    'papaparse__5.4.1',
    'pure-rand__6.1.0',
    'react-dom__18.3.1',
    'react__18.3.1',
    'simple-statistics__7.8.3',
    'type-fest__4.23.0',
    'zod__3.23.6'
  ],
  outdir: 'dist'
};
